services:
    backend:
        image: amazoncorretto:24
        container_name: backend
        volumes:
            - ./backend:/app
        working_dir: /app
        command: java -jar Backend.jar
        ports:
            - "7070:7070"
        restart: unless-stopped
